
<?php
/**
 * The template for displaying the comments block (wrapper for the comments template)
 *
 * @package Angilla
 * @since Angilla 1.0.0
 */
?>
<div id="angi-comments" class="comments-area <?php angi_fn_echo('element_class') ?>" <?php angi_fn_echo('element_attributes') ?>>
  <?php do_action('angi_before_comments_template') ?>
  <?php
  /* We kinda need to do this this way as the WP_Comment_Query is generated by the function below */
  comments_template( '' , true ) ?>
  <?php do_action('angi_after_comments_template') ?>
</div>